import 'dotenv/config';

export const config = {
  GEMINI_API_KEY: process.env.GEMINI_API_KEY,
  REMOVE_BG_API_KEY: process.env.REMOVE_BG_API_KEY,
  OWNER_NUMBER: process.env.OWNER_NUMBER,
  BOT_NAME: process.env.BOT_NAME || 'WhatsApp AI Bot',
  GEMINI_MODEL: 'gemini-3.1-flash-lite',
  MAX_HISTORY: 10,
  DB_PATH: './chat_history.db',
  TIMEZONE: process.env.TIMEZONE || 'Asia/Jakarta',

  GOOGLE_DRIVE_ENABLED: process.env.GOOGLE_DRIVE_ENABLED === 'true',
  GOOGLE_DRIVE_TYPE: process.env.GOOGLE_DRIVE_TYPE || 'service_account',
  GOOGLE_DRIVE_CREDENTIALS_PATH: process.env.GOOGLE_DRIVE_CREDENTIALS_PATH || '',
  GOOGLE_DRIVE_CLIENT_EMAIL: process.env.GOOGLE_DRIVE_CLIENT_EMAIL || '',
  GOOGLE_DRIVE_PRIVATE_KEY: process.env.GOOGLE_DRIVE_PRIVATE_KEY || '',
  GOOGLE_DRIVE_CLIENT_ID: process.env.GOOGLE_DRIVE_CLIENT_ID || '',
  GOOGLE_DRIVE_CLIENT_SECRET: process.env.GOOGLE_DRIVE_CLIENT_SECRET || '',
  GOOGLE_DRIVE_REFRESH_TOKEN: process.env.GOOGLE_DRIVE_REFRESH_TOKEN || '',
  GOOGLE_DRIVE_REDIRECT_URI: process.env.GOOGLE_DRIVE_REDIRECT_URI || 'http://localhost',
  GOOGLE_DRIVE_FOLDER_ID: process.env.GOOGLE_DRIVE_FOLDER_ID || '',

  GOOGLE_DRIVE_BACKUP_ENABLED: process.env.GOOGLE_DRIVE_BACKUP_ENABLED === 'true',
  GOOGLE_DRIVE_BACKUP_CRON: process.env.GOOGLE_DRIVE_BACKUP_CRON || '0 0 * * *',
  GOOGLE_DRIVE_BACKUP_FOLDER_ID: process.env.GOOGLE_DRIVE_BACKUP_FOLDER_ID || '',
  GOOGLE_DRIVE_BACKUP_ON_START: process.env.GOOGLE_DRIVE_BACKUP_ON_START === 'true',
};
